sensor: # Numeric Sensors
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_sensor
    unit_of_measurement: dBm
  - platform: internal_temperature
    name: "CPU Temp"
    unit_of_measurement: °C
    id: cpu_temp
  - platform: uptime
    type: seconds
    name: "ESP Uptime"
    filters:
      - multiply: 0.0000115741
    unit_of_measurement: "d"
    accuracy_decimals: 4

text_sensor: # Text Sensors
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:ip-outline
      id: main_ip

button: # Button Actions
  - platform: restart
    name: "Restart"
    id: restart_button
