substitutions:
  color_black: "0x000000"
  color_white: "0xFFFFFF"
  color_light_gray: "0xB0BEC5"
  color_blue: "0x0082FF"
  color_green: "0x4CAF50"
  color_bright_green: "0x00FF00"
  color_red: "0xFF0000"
  color_amber: "0xFFC300"
  color_cyan: "0x00FFFF"
  glyphs_max: " /:1234567890.°?%-abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZµ³"
  glyphs_min: " 1234567890.°FfCcpPmMnaN?%-"

esphome:
  on_boot:
    - priority: 300
      then:
        - delay: 1s
        - if:
            condition:
              light.is_on: main_backlight
            then:
              - lvgl.page.show: main_page
            else:
              - lvgl.page.show: blank_page
        - delay: 1s
        - script.execute: # still testing
            id: apply_display_rotation
            rotation: !lambda "return id(display_rotation).current_option();"

select:
  - platform: template
    name: "Display Rotation"
    id: display_rotation
    icon: "mdi:screen-rotation"
    entity_category: CONFIG
    optimistic: true
    restore_value: true
    initial_option: "0"
    options:
      - "0"
      - "90"
      - "180"
      - "270"
    set_action:
      - script.execute:
          id: apply_display_rotation
          rotation: !lambda "return x;"

button: # LVGL Button Actions
  - platform: template  
    name: "Refresh Screen"
    icon: mdi:refresh
    on_press:
      - component.update: main_display
  - platform: template  
    name: "Pause LVGL"
    icon: mdi:pause
    on_press:
      - lvgl.pause: 
  - platform: template  
    name: "Resume LVGL"
    icon: mdi:play
    on_press:
      - lvgl.resume:
  - platform: template  
    name: "Next Page"
    icon: mdi:page-next-outline
    on_press:
      - lvgl.page.next: 
  - platform: template  
    name: "Previous Page"
    icon: mdi:page-previous-outline
    on_press:
      - lvgl.page.previous:
  - platform: template
    name: Show Snow
    icon: mdi:image-refresh-outline
    on_press:
      - lvgl.pause:
          show_snow: true
  - platform: template
    name: "Reset LVGL Idle Timer"
    icon: mdi:timer-sand
    on_press:
      then:
        - lambda: |-
            lv_disp_trig_activity(NULL);
            
text_sensor:
  - platform: template
    name: "LVGL Current Page"
    id: current_lvgl_page
    icon: mdi:tablet-dashboard
    update_interval: never
    
interval:
  - interval: 30min
    then:
      - component.update: main_lvgl
      - script.execute: update_lvgl_page
      
lvgl:
  id: main_lvgl
  on_draw_end:
    - script.execute: update_lvgl_page
  on_idle:
    - timeout: 15s
      then:
        - if:
            condition:
              light.is_on: main_backlight
            then:
              - lvgl.page.show: 
                  id: main_page
              - logger.log: "LVGL has been idle for 15 seconds, switching to main page"
            else:
              - logger.log: "LVGL has been idle for 15 seconds, but backlight is off so page switch was skipped"
    - timeout: 60s
      then:
        - if:
            condition:
              lambda: |-
                auto now = id(sntp_time).now();
                if (!now.is_valid()) return false;

                int minutes = now.hour * 60 + now.minute;

                // Night window: 22:00 → 04:30 (wraps midnight)
                return (minutes >= (22 * 60)) || (minutes < (4 * 60 + 30));
            then:
              - light.turn_off: main_backlight
              - logger.log: "Time appears to be between 22:00 & 04:30, turning off backlight"
            else:
              - logger.log: "Time appears to not be between 22:00 & 04:30, keeping backlight on"
  pages: # Add a blank page
    - id: blank_page
      skip: true
      bg_color: ${color_black}
      
script:
  - id: update_lvgl_page
    then:
      - if:
          condition:
            lvgl.page.is_showing: main_page
          then:
            - text_sensor.template.publish:
                id: current_lvgl_page
                state: "Main Page"
          else:
            - if:
                condition:
                  lvgl.page.is_showing: second_page
                then:
                  - text_sensor.template.publish:
                      id: current_lvgl_page
                      state: "Second Page"
                else:
                  - if:
                      condition:
                        lvgl.page.is_showing: blank_page
                      then:
                        - text_sensor.template.publish:
                            id: current_lvgl_page
                            state: "Blank Page"
                      else:
                        - text_sensor.template.publish:
                            id: current_lvgl_page
                            state: "Unknown"
                            
  - id: apply_display_rotation
    parameters:
      rotation: std::string
    then:
      - if:
          condition:
            lambda: 'return rotation == "90";'
          then:
            - lvgl.display.set_rotation:
                rotation: 90
          else:
            - if:
                condition:
                  lambda: 'return rotation == "180";'
                then:
                  - lvgl.display.set_rotation:
                      rotation: 180
                else:
                  - if:
                      condition:
                        lambda: 'return rotation == "270";'
                      then:
                        - lvgl.display.set_rotation:
                            rotation: 270
                      else:
                        - lvgl.display.set_rotation:
                            rotation: 0
