esp32:
  variant: ESP32S3
  framework:
    type: esp-idf
    
psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false
  
packages:
  rgb_led: !include
    file: ../rgb_led.yaml
    vars:
      rgb_led_gpio: GPIO48
      rgb_led_chipset: ws2812
      rgb_led_channel_colors: GRB
      rgb_led_num_leds: "1"
      rgb_led_rmt_symbols: "48"
            
binary_sensor:
  - platform: gpio
    id: boot_button
    name: "Boot Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true

debug:
  update_interval: 15s

sensor:
  - platform: debug
    psram:
      name: "Free PSRAM"
