script:
  - id: interaction
    mode: restart
    then:
      - lambda: |-
          lv_disp_trig_activity(NULL);
      - logger.log: "Resetting idle timer (interaction)"
      - if:
          condition:
            light.is_off: main_backlight
          then:
            - light.turn_on: main_backlight
            - logger.log: "Backlight was off, turning on."
          else:
            - if:
                condition:
                  and:
                    - light.is_on: main_backlight
                    - lvgl.page.is_showing: second_page
                then:
                  - lvgl.page.show: main_page
                  - logger.log: "Second page was showing, switched to main."

  - id: next_page
    mode: restart
    then:
      - lambda: |-
          lv_disp_trig_activity(NULL);
      - logger.log: "Resetting idle timer (next_page)"
      - if:
          condition:
            light.is_off: main_backlight
          then:
            - light.turn_on: main_backlight
            - logger.log: "Backlight was off, turning on."
          else:
            - if:
                condition:
                  and:
                    - light.is_on: main_backlight
                    - lvgl.page.is_showing: main_page
                then:
                  - lvgl.page.show: second_page
                  - logger.log: "Main page was showing, switched to second."
                else:
                  - if:
                      condition:
                        and:
                          - light.is_on: main_backlight
                          - lvgl.page.is_showing: second_page
                      then:
                        - lvgl.page.show: main_page
                        - logger.log: "Second page was showing, switched to main."

  - id: interaction_fade
    mode: restart
    then:
      - lambda: |-
          lv_disp_trig_activity(NULL);
      - logger.log: "Resetting idle timer (interaction_fade)"
      - if:
          condition:
            light.is_off: main_backlight
          then:
            - light.turn_on: main_backlight
            - logger.log: "Backlight was off, turning on."
          else:
            - if:
                condition:
                  and:
                    - light.is_on: main_backlight
                    - lvgl.page.is_showing: second_page
                then:
                  - lvgl.resume:
                  - lvgl.page.show:
                      id: main_page
                      animation: FADE_OUT
                      time: 1500ms
                  - logger.log: "Second page was showing, switched to main (with fade)."
                  
  - id: next_page_fade
    mode: restart
    then:
      - lambda: |-
          lv_disp_trig_activity(NULL);
      - logger.log: "Resetting idle timer (next_page_fade)"
      - if:
          condition:
            light.is_off: main_backlight
          then:
            - light.turn_on: main_backlight
            - logger.log: "Backlight was off, turning on"
          else:
            - if:
                condition:
                  and:
                    - light.is_on: main_backlight
                    - lvgl.page.is_showing: main_page
                then:
                  - lvgl.page.show: second_page
                  - logger.log: "Main page was showing, switched to second."
                else:
                  - if:
                      condition:
                        and:
                          - light.is_on: main_backlight
                          - lvgl.page.is_showing: second_page
                      then:
                        - lvgl.page.show:
                            id: main_page
                            animation: FADE_OUT
                            time: 1500ms
                        - logger.log: "Second page was showing, switched to main (with fade out)."
