esp32:
  variant: ESP32
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true
      minimum_chip_revision: "3.1"

packages:
  status_led: !include
    file: ../status_led.yaml
    vars:
      status_led_gpio: GPIO2
      status_led_inverted: "false"
      status_led_frequency: "10kHz"
      status_led_max_power: "0.5"
    
binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Boot Button"
