# waveshare 7” ESP32-S3N8R8 Capacitive Touch Display 1024×600
# 512KB SRAM and 384KB ROM, with onboard 16MB Flash and 8MB PSRAM
# https://www.waveshare.com/esp32-s3-lcd-7b.htm
# Hardware configuration file

esp32:
  variant: ESP32S3
  framework:
    type: esp-idf
  flash_size: 16MB
  cpu_frequency: 240MHZ

external_components:
  - source: github://pr#10071
    components: [waveshare_io_ch32v003]
    refresh: 30min

waveshare_io_ch32v003:
  - id: wave_io
    address: 0x24
    i2c_id: main_i2c 

output:
  - platform: waveshare_io_ch32v003
    id: main_backlight_output
    inverted: true
    zero_means_zero: true
    safe_pwm_levels:  # 0...255
      min_value: 0    # Default: 0
      max_value: 247  # Default: 247. Safe max for ESP32S3-Touch-LCD-7B circuitry

  - platform: ledc
    pin: GPIO6
    id: buzzer

switch:
 - platform: gpio
   id: exio2
   restore_mode: RESTORE_DEFAULT_ON
   pin: 
     waveshare_io_ch32v003: wave_io
     number: 2
     mode: 
       output: true

light:
  - platform: monochromatic
    output: main_backlight_output
    name: Display Backlight
    id: main_backlight
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 750ms
    on_turn_on: 
      then:
        - lvgl.page.show: main_page
        - switch.turn_on: exio2
        - logger.log: "LVGL resumed, exio2 turned on"
    on_turn_off: 
      then:
        - lvgl.page.show: blank_page
        - switch.turn_off: exio2
        - logger.log: "LVGL paused and set to blank screen"   

i2c:
  - id: main_i2c
    sda: 8
    scl: 9
  
psram:
  mode: octal
  speed: 80MHz
  
sensor: # ADC
  - platform: waveshare_io_ch32v003
    name: "ADC"
    id: wave_adc
    # Convert ADC value to voltage (10-bit ADC, 3.3V reference, and 3:1 voltage divider)
    # value = adc * 3 * 3.3V / 1023.0
    reference_voltage: 9.9  # so returned value is ADC * 9.9 / 1023.0

touchscreen:
  platform: gt911
  id: gt911_touchscreen
  display: main_display
  i2c_id: main_i2c
  interrupt_pin: GPIO4
  reset_pin:
    waveshare_io_ch32v003: wave_io
    number: 1
    mode: OUTPUT

display:
  - platform: mipi_rgb
    model: RPI
    id: main_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 1024
      height: 600
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    reset_pin:
      waveshare_io_ch32v003: wave_io
      number: 3
    hsync_back_porch: 152
    hsync_front_porch: 48
    hsync_pulse_width: 162

    vsync_back_porch: 13
    vsync_front_porch: 3
    vsync_pulse_width: 45
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7